apiVersion: v1
kind: Pod
metadata:
  name: stress
  annotations:
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: app
    image: nginx
    command: 
      - /bin/sh
      - -c
      - |
        apt-get update
        apt-get install stress
        stress --vm 1 --vm-bytes 2.5G
    resources:
      requests:
        memory: "2560Mi"
        cpu: "2500m"
      limits:
        memory: "2560Mi"
        cpu: "2500m"
