apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  annotations:
    configmanagement.gke.io/managed-by-hub: "true"
    configmanagement.gke.io/update-time: "1687251160"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"configsync.gke.io/v1beta1","kind":"RootSync","metadata":{"annotations":{"configmanagement.gke.io/managed-by-hub":"true","configmanagement.gke.io/update-time":"1686121902"},"creationTimestamp":"2023-05-22T09:01:56Z","generation":5,"labels":{"app.kubernetes.io/managed-by":"anthosconfigmanagement.googleapis.com"},"name":"root-sync","namespace":"config-management-system","resourceVersion":"24629181","uid":"9b722986-10cf-42f1-9a8e-24c974448a6d"},"spec":{"git":{"auth":"none","branch":"main","dir":"config-sync/root9","period":"15s","repo":"https://github.com/himanigulati-test/acm-test-repo","revision":"HEAD","secretRef":{}},"override":{},"sourceFormat":"unstructured","sourceType":"git"},"status":{"conditions":[{"lastTransitionTime":"2023-06-18T06:52:35Z","lastUpdateTime":"2023-06-18T06:52:35Z","status":"False","type":"Reconciling"},{"commit":"3af2ff30c0de08bc26647d787a8dec8d6a0dd2c1","errorSummary":{},"lastTransitionTime":"2023-06-20T08:52:39Z","lastUpdateTime":"2023-06-20T08:52:39Z","message":"Sync Completed","reason":"Sync","status":"False","type":"Syncing"}],"lastSyncedCommit":"3af2ff30c0de08bc26647d787a8dec8d6a0dd2c1","observedGeneration":5,"reconciler":"root-reconciler","rendering":{"commit":"3af2ff30c0de08bc26647d787a8dec8d6a0dd2c1","errorSummary":{},"gitStatus":{"branch":"main","dir":"config-sync/root","repo":"https://github.com/himanigulati-test/acm-test-repo","revision":"HEAD"},"lastUpdate":"2023-06-18T06:52:31Z","message":"Rendering skipped"},"source":{"commit":"3af2ff30c0de08bc26647d787a8dec8d6a0dd2c1","errorSummary":{},"gitStatus":{"branch":"main","dir":"config-sync/root","repo":"https://github.com/himanigulati-test/acm-test-repo","revision":"HEAD"},"lastUpdate":"2023-06-20T08:52:39Z"},"sync":{"commit":"3af2ff30c0de08bc26647d787a8dec8d6a0dd2c1","errorSummary":{},"gitStatus":{"branch":"main","dir":"config-sync/root","repo":"https://github.com/himanigulati-test/acm-test-repo","revision":"HEAD"},"lastUpdate":"2023-06-20T08:52:39Z"}}}
  creationTimestamp: "2023-05-22T09:01:56Z"
  generation: 7
  labels:
    app.kubernetes.io/managed-by: anthosconfigmanagement.googleapis.com
  name: root-sync2
  namespace: config-management-system
  resourceVersion: "24636829"
  uid: 9b722986-10cf-42f1-9a8e-24c974448a6d
spec:
  git:
    auth: none
    branch: main
    dir: config-sync/root
    period: 15s
    repo: https://github.com/himanigulati-test/acm-test-repo
    revision: HEAD
    secretRef: {}
  override: {}
  sourceFormat: unstructured
  sourceType: git
